### ISSUE TITLE
how do I tell which genomes are installed in bcbio

### ISSUE THREAD

**Issue by jnhutchinson** [hbc/knowledgebase#16]
and which version of the genome are they?

**Comment by mistrm82** [comment]
Merging this with #21 

Check installed genomes and try to sort them. There are different versions and not clear if they're updated or even useful.

**Comment by mistrm82** [comment]
Also, I think this is a good starting point and people can start adding to it?

https://github.com/hbc/knowledgebase/blob/master/computing/bcbio/bcbio_genomes.md

**Comment by naumenko-sa** [comment]
https://github.com/hbc/knowledgebase/blob/master/bcbio/bcbio_genomes.md
https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes
