### ISSUE TITLE
how do I run the new automated QC (via bcbioRNASeq) from bcbio

### ISSUE THREAD

**Issue by jnhutchinson** [hbc/knowledgebase#17]

**Comment by roryk** [comment]
https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=bcbiornaseq#rna-sequencing has documentation about how to do this, and how to set the interestingGroups. You also need to turn bcbiornaseq on via `tools_on: [bcbiornaseq]`. I'll fix the formatting of the documentation.
