### ISSUE TITLE
Sort genomes in O2/Odyssey. 

### ISSUE THREAD

**Issue by vbarrera** [hbc/knowledgebase#21]
Check installed genomes and try to sort them. There are different versions and not clear if they're updated or even useful.

**Comment by jnhutchinson** [comment]
Can we combine this with https://github.com/hbc/knowledgebase/issues/16 somehow?

**Comment by lpantano** [comment]
you can close it and modify  the other issues with the information from both.

sent not from my computer

**Comment by mistrm82** [comment]
closing this since I have referenced it in #16  to merge the content together
