### ISSUE TITLE
suggestion: useful R packages/utilities

### ISSUE THREAD

**Issue by jnhutchinson** [hbc/knowledgebase#29]
I think it would be nice to have a section listing some useful R packages that people use to make consults easier (aside from the usual tidyverse packages)

Examples:
rio - easy import/export of various file types, including Excel
janitor - good for cleaning up and standardizing data
colorout - text color highlighting for R in terminal mode

almost anything Hadley Wickham has ever worked on, lol

**Comment by naumenko-sa** [comment]
there is https://github.com/hbc/knowledgebase/blob/master/r/R-tips-and-tricks.md for that.
