### ISSUE TITLE
Lightweight bcbioRNASeq

### ISSUE THREAD

**Issue by roryk** [hbc/knowledgebase#36]
This issue is for a discussion of what it would take and whether we should implement a more lightweight bcbioRNASeq. This is partially a backup plan for if it turns out bcbioRNASeq isn't a workable long term solution.

We're moving towards having the end point of a bcbio RNA-seq run to be a SummarizedExperiment object that has the data relevant to running transcript and gene differential expression analyses and to handle everything else downstream. Right now bcbio-nextgen does that via bcbioRNASeq, which seems like it is stable and works well.

The code in bcbioRNASeq is very clean and nice, but it is very complicated to work with. Problems that have cropped up with bcbioRNASeq are:

1) it is very hard to fix something when an edge case is reached to get a project moving again
2) adding new features which should be straightforward, such as a new QC plot from existing data is very hard
3) the code has historically not been back compatible, making adding figures to old analyses extremely difficult
4) you need to be an R expert to understand the code

This is preventing folks from working on the code and is slowing us down when there is a bug, since it takes forever to fix the code and generally requires an extreme R expert to dig into the problem.

Victor and Lorena have an alternative workflow that is simpler and more like the way we were doing it before via bcbio.rnaseq. The steps are:

1. Generate a SummarizedExperiment from a bcbio run with [bcbioLite](https://github.com/vbarrera/bcbioLite)
2. Annotate the SummarizedExperiment object with AnnotationHub. [Example](https://code.harvard.edu/HSPH/hbc_gchurch_rnaseq_stemcells_elephant/blob/master/load.R#L22)
3. Run a stripped down QC report, that has the code for the plots exposed so folks can just edit the code if they need to. [Example](https://code.harvard.edu/HSPH/hbc_gchurch_rnaseq_stemcells_elephant/blob/master/qc.Rmd)

I would be down for implementing an alternate version of the SummarizedExperiment object coming from bcbio, using this workflow with the aim of swapping over to this once it seems like we can generate comparable quality control reports from bcbio. We have users that are using the quality control report for their daily work, so what we generate would have to be comparable to that report before we could swap in it. So for a while it would be in parallel.

**Comment by jnhutchinson** [comment]
Thanks rory, for starting this.

Focusing on the example for annotating the Summarized experiment with AnnotationHub, is there potential for putting all those lines as a single, accessible function (as opposed to an S4 method)? Or is that what's being suggested?

**Comment by jnhutchinson** [comment]
Hey @roryk has this basically been achieved with the bcbiolite method Victor is doing?

**Comment by roryk** [comment]
Yup!
