### ISSUE TITLE
Detecting strandedness in RNAseq from Salmon output

### ISSUE THREAD

**Issue by jnhutchinson** [hbc/knowledgebase#37]
I always find it difficult to remember how to check strandedness of an RNA-seq run from the Salmon data. Would be great to have it written up

**Comment by roryk** [comment]
This is something we could do up front-- grab a subset of the reads, map with Salmon and parse the JSON in the log file to figure out what is the most likely orientation. The log file has a list of all of the orientations which we can use to set the strandedness properly.

**Comment by naumenko-sa** [comment]
https://github.com/hbc/knowledgebase/blob/master/rnaseq/strandedness.md
