### ISSUE TITLE
migrate project set up document to md

### ISSUE THREAD

**Issue by lpantano** [hbc/knowledgebase#6]
Needs to migrate this document:

Updated document: https://drive.google.com/open?id=1gbSX_S43Y2OQaSrNDOlDvrhJb1tlFgBY
into markdown format inside this repo.

**Comment by vbarrera** [comment]
Notes on this:
- the github repo doesn't include the name of the PI. I think that was something desirable. Should we add that?
- Don't we want to include the researcher (postdoc probably) to the naming scheme. I have a few researchers coming from the same lab (PI) and it helps to sort them out.

**Comment by sjhosui** [comment]
For the github repo, I would like to the see the PI last name directly after hbc. I don't think including the researcher name is necessary.

**Comment by jnhutchinson** [comment]
Migrated to Markdown and now cleaning up formatting and errors in logical flow left over from moving sections around

**Comment by jnhutchinson** [comment]
Victor, apologies for misunderstanding taht the github repo didn't have the PI's last name. I thought you were referring to the PI's firstname. I've added the PI's last name to the naming scheme, which I had neglected to do before.

**Comment by jnhutchinson** [comment]
Updated document: https://drive.google.com/open?id=1gbSX_S43Y2OQaSrNDOlDvrhJb1tlFgBY

**Comment by jnhutchinson** [comment]
moved doc to repo and added link in README

**Comment by lpantano** [comment]
this is already in the main repo. Thanks!
