### ISSUE TITLE
Add a template for acknowledgements

### ISSUE THREAD

**Issue by rkhetani** [hbc/knowledgebase#69]
It would be nice to have templates for asking researchers to acknowledge us and the various funders when they write a manuscript or similar.

**Comment by jnhutchinson** [comment]
@lpantano didn't we write these up previously to be part of report templates?

**Comment by lpantano** [comment]
this is mentioned here: https://github.com/hbc/knowledgebase/blob/master/admin/guides/setting_up_an_analysis_guidelines.md#adding-funding-section-to-reports

They are functions that add the specific text to the template.

**Comment by jnhutchinson** [comment]
Added a doc to admin for this
