### ISSUE TITLE
lpantano_knowledge

### ISSUE THREAD

**Issue by lpantano** [hbc/knowledgebase#8]
I have all in hbcACB:

* information that apply to all templates: http://bioinformatics.sph.harvard.edu/hbcABC/articles/general_start.html
* List of templates right now: http://bioinformatics.sph.harvard.edu/hbcABC/articles/list_of_templates.html
* single cell custom templates: http://bioinformatics.sph.harvard.edu/hbcABC/articles/singlecell-tutorial.html

**Comment by jnhutchinson** [comment]
Why is the template repo called hbcACB? It's really hard to remember the name.
